### ISSUE TITLE
v2.0 planning

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#1128]
- [x] issue sweep
- [x] start release notes
- [x] update `whats-new.rst`
- [x] think on what else we want to prioritize while we are breaking all the things

**Comment by mr-c** [comment]
I did a manual releasetest on OS X using python.org's 3.3 and 3.4 release and all was well

**Comment by mr-c** [comment]
remaining code changes
- [ ] Remove get_kadian_count functionality. #1034
- [ ] Verify that n_occupied etc. numbers are correct and saved in both countgraph & nodegraph #1093
- [ ] Save _n_occupied and _n_unique_kmers in Hashtable descendants... maybe? #1194

Rest are documentation only

**Comment by ctb** [comment]
- [ ] update whats-new with fixed bug from #1194 / 15651da, in which number of unique k-mers reported had been systematically underestimated by CountingHash/Countgraph (so, e.g. load-into-counting unique k-mers reported was generally significantly underestimated)

**Comment by mr-c** [comment]
- [ ] wait for DOI from F1000?

**Comment by mr-c** [comment]
- [ ] update file magic

**Comment by mr-c** [comment]
rc4 passes the BatLab tests on the supported platforms. As expected I had to remove Debian6, RHEL6, SL6, Ubuntu 12, and OS X 7 from the test list

**Comment by mr-c** [comment]
the `doc/run-corn-50m.sh` script still works in rc4

**Comment by mr-c** [comment]
@ctb Looks like you're working on the acceptance tests. Shall I give that a try or wait for you?

**Comment by ctb** [comment]
On Thu, Aug 27, 2015 at 04:00:12PM -0700, Michael R. Crusoe wrote:
> @ctb Looks like you're working on the acceptance tests. Shall I give that a try or wait for you?

The ctb branch works fine through assembly, AFAICT.  Not planning to fix
the rest at the moment.

**Comment by mr-c** [comment]
rc4 & rc5 cut; coverity scan has passed.

**Comment by mr-c** [comment]
rather, rc5 and rc6

**Comment by mr-c** [comment]
BaTLab tests passed

**Comment by mr-c** [comment]
the testpypi service isn't working for me and the acceptance testing is gated on Athyra being restored

**Comment by mr-c** [comment]
Acceptance tests pass (rc6)

**Comment by mr-c** [comment]
testpypi now working for me under Debian Unstable & Ubuntu 14.04 (but not Debian Testing)

Alas it has surfaced another wrinkle with the script version test. Drafting a pull request now

**Comment by mr-c** [comment]
`--version` bug fixed in rc8, acceptance tests passed for rc8.

**Comment by mr-c** [comment]
And the release is out!
