### ISSUE TITLE
Code Review Checklist

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#196]
draft:
- [ ] Is it mergable
- [ ] Did it pass the tests?
- [ ] If it introduce new functionality in scripts/ is it tested? Check for code coverage
- [ ] Is it well formatted? Look at `pep8`/`pylint`, `cppcheck`, and `make doc` output. Use `autopep8` and `astyle -A10` if needed. 
- [ ] Is it documented in the Changelog?
