### ISSUE TITLE
0.8 release checklist

### ISSUE THREAD

**Issue by mr-c** [dib-lab/khmer#262]
PR's and issues required for release:
#237 [galaxy bits],
#244 [switch default branch from master to legacy]
- [x] Check for updates to ez_setup.py and versioneer.
- [x] Update docs/known-issues.txt with any bugs not being fixed in this release
- [x] Review the git logs since the last release and diffs (if needed) and ensure
  that the Changelog is up to date.
- [x] Verify that the build is clean
- [x] Tag master w/ `v0.8-rc1`
- [x] Test the release candidate on Linux & OS X (use batlab.org for this?)
- [x] Publish the new release on the testing PyPI server
- [x] Test the PyPI release in a new virtualenv
- [x] Create the final tag `v0.8`
- [x] Publish the new release on PyPI including a wheel for OS X
- [x] Publish the final tag it to github
- [x] Announce the new release via twitter, khmer@lists.idyll.org & khmer-announce@lists.idyll.org
