### ISSUE TITLE
screed 1.0 API thoughts

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#791]
Things that should be dealt with before screed 1.0 -- please add to this issue.

- [x] Slicing of screed records (#768)
- [x] A plan for synching of quality attribute details between khmer and screed (#769)
- [x] Putting in place tests for and fixes for many broken FASTQ formats (#760, #108)
- [x] len(record) should work (or fail obviously) #705 - screed#18 needs review.
- [x] Make a nicer way to create new screed Record objects (#767)

- [x] Is #625 still relevant or should it be closed?
- [x] Also: remove description, maybe. #820

**Comment by ctb** [comment]
Also: remove description, maybe. #820

**Comment by mr-c** [comment]
- [ ] delete the redefinition of `open` in `screed/openscreed.py`

**Comment by ctb** [comment]
Disagree; it's only a problem if someones does 'from screed import *' which is UnPythonic. I like 'open'.

**Comment by mr-c** [comment]
It proved to be a stumbling block to Camille and I during a `pdb` debugging session. *shrug*

**Comment by ctb** [comment]
All done.
